### PR TITLE
Add rabby wallet

### PR DESCRIPTION
**Pull request by Agastya18**
this pr introduce rabby wallet integration using wagmi , for issue #38

## Demo

https://github.com/user-attachments/assets/8012efc8-ed97-4f7b-a67f-f458a8fb7627

### CODE REVIEW

**Comment by DS-jr** [comment]
@Agastya18 , thanks for your contribution & PR! 

About the prototype in your screencast video: 

Is it integrated in Telegram & working inside Telegram Mini App? 

Or is it working only in a regular browser now?

**Comment by DS-jr** [comment]
@Agastya18 , got it, thanks. 

Have you already tried to build simplest possible Telegram Mini App prototype (as described in "How to contribute") with Rabby? 

It'll be relatively easy/quick, if your prototype already works in regular browser.  

Any template/library for generating Telegram Mini App can be used to simplify & save time.

**Comment by Agastya18** [comment]
i have tried to built bot, but it is not working correctly,  let me fix the it

**Comment by DS-jr** [comment]
@Agastya18 , agreed! 

Appreciate your quick replies. 

Please, keep us informed here about your progress

**Comment by Agastya18** [comment]
Sure!!

**Comment by Agastya18** [comment]
finally its working,  bot link: https://t.me/rabbyeth_bot/rabbywallet
Screenshot 2024-12-11 at 9 30 07 PM

**Comment by DS-jr** [comment]
@Agastya18 , thank you for building TG Mini App prototype! 

Currently this prototype works properly via web version of TG in browser, not via TG mob app version, correct?

**Comment by Agastya18** [comment]
any updation you want ??

**Comment by DS-jr** [comment]
It is ok, web version prototype is enough. 

Appreciate your contribution & quick iterations! 💪

**Comment by DS-jr** [comment]
@Agastya18 , if you'd like to stay in touch via Telegram - we can exchange TG nicknames here

**Comment by Agastya18** [comment]
my telegram username😊 : @agastyagaur

**Comment by DS-jr** [comment]
@Agastya18 , thanks, will text you in TG

**Pull request merged**
