### PR TITLE
add-metamask-tg-wallet

### PR DESCRIPTION
**Pull request by Agastya18**
add metamask wallet for issue #36

## Screenshot
Screenshot 2024-12-14 at 9 53 45 PM

### CODE REVIEW

**Comment by DS-jr** [comment]
@Agastya18 , could you please add the link of working TG Mini App prototype that you've built for this Issue?

**Comment by Agastya18** [comment]
Yep 😊

**Comment by DS-jr** [comment]
Thanks, @Agastya18 !

**Comment by Agastya18** [comment]
tg_bot: https://t.me/metamask5_bot/test

**Comment by Agastya18** [comment]
i have send my resume in telegram😅

**Comment by DS-jr** [comment]
@Agastya18 , thank you!

**Pull request merged**
