### PR TITLE
Revert "add metamask tg wallet"

### PR DESCRIPTION
**Pull request by Agastya18**
Reverts ctrlsa/smart-contract-wallet-Ethereum-Account-Abstraction-Telegram#40

### CODE REVIEW

**Comment by DS-jr** [comment]
@Agastya18 , could you, please, briefly explain why PR #40 had to be reverted?

**Comment by Agastya18** [comment]
There was the problem with the first pr , then I revert it and create new pr 😅

**Comment by DS-jr** [comment]
@Agastya18 , got it, thanks for clarifying.

**Comment by DS-jr** [comment]
@Agastya18  

For our next iterations: let's please move PRs through reviews before merging, so new contributions are accepted to Main branch by reviewer. 

Will add this step to "How to contribute", as it is not explicitly written there now.

**Pull request merged**
